### ISSUE TITLE
Fix transaction

### ISSUE THREAD

**Issue by s154302** [s154302/PortalKredit#36]
The commit check should be changed to:
(oldSendBalance - oldReciBalance) == (newSendBalance - newReciBalance)
This requires 2 new SQL statements at the beginning of the method to extract the old balances from the database. 

Furthermore I don't think it is possible to create the transactions in a separate method when we want to setAutoCommit(false). So the createTransaction method should be deleted and its contents moved to the transaction method.

**Comment by s154302** [comment]
(oldSendBalance + oldReciBalance) == (newSendBalance + newReciBalance)

**Comment by tk7000** [comment]
Also need a to check if the transactions are added to the DB before commiting the transfer
